### ISSUE TITLE
Assistant Audio Doesn't Always Play

### ISSUE THREAD

**Issue by tankerkiller125** [ItsWendell/google-assistant-desktop-client#4]
Sometimes the assistant audio won't play until you ask it another question. Seems to be a bug with the audio or something. This happens most often with the "I don't know how to help with that" audio

**Comment by E3V3A** [comment]
yeap, happens to me too quite often. NEver any useful error. 
But I did notice that it [seem like the assistant is recording itself](https://github.com/eouia/MMM-Assistant/issues/46), while talking... 
Not sure how to prevent this.

**Comment by ItsWendell** [comment]
@E3V3A Not sure how this is related to this particular project, interesting project btw for the magic mirror!

What could be cool for the magic mirror project is rendering the HTML5 output into the mirror like I'm doing in a new version / branch of the Google Assistant for Desktop app: [See new branch here.](https://github.com/WMisiedjan/google-assistant-desktop-client/tree/feature/html5-output)

![knipsel](https://user-images.githubusercontent.com/591280/39971930-421edf7e-5705-11e8-93bb-b81c39eb7975.JPG)

**Comment by tankerkiller125** [comment]
@WMisiedjan Some issues with the HTML5 branch needs the Linux icon to be set (just add `|| 'linux'` to the darwin line) and also the background is not transparent and the response window is not fullscreen. I don't know if there's a microphone issue or not? Can't tell if that part is implemented or not yet.

**Comment by ItsWendell** [comment]
@tankerkiller125 Thanks for your feedback and checking out the project, the HTML5 branch still needs some work indeed, I actually made the response window not full screen on purpose so that you can actually click it away at the top of your screen when you don't wanna look at it for more than 5 - 20 seconds, depending on the response, I'll look for an alternative for this.

As for the Linux icon I'll make an PR request soon to fix the Linux icon issue, I didn't got time to connect the microphone yet since I've recently moved the project to another library for the assistant, will do another update this week when I get round to it. Thanks 👍

**Comment by ItsWendell** [comment]
@tankerkiller125 I just switched to Linux since I had some issues with my laptop, just did some updates and the microphone should be working now.

I also improved the UX since responseWindow will now close once you click on the shadow / transparent part of the responseWindow!

It overall needs a little bit more testing and fine-tuning this branch but it's almost ready to be pushed to the main develop!

**Comment by ItsWendell** [comment]
@tankerkiller125 @E3V3A I just released version 0.3.0 as the main develop branch! Custom commands are working again, this bug is solved in the audio player and the assistant only starts listening when the assistant is done 'talking'!

See: https://github.com/WMisiedjan/google-assistant-desktop-client/commit/e63cb9201041cff4862ecbf28cadb0d2af964df6

**Comment by WMisiedjan** [comment]
Solved.
